# Generated by Django 4.2.3 on 2023-08-01 09:23

from django.db import migrations, models
import researchpapermanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('researchpapermanagement', '0004_remove_filemodel_facultypublication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, validators=[researchpapermanagement.models.validate_name]),
        ),
    ]
